//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 03:01:15 PM EST 
//


package com.comcast.technucleus.application.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eisrecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eisrecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MaxID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ism_c_Serial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="iim_c_Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eisrecord", propOrder = {

})
public class Eisrecord {

    @XmlElement(name = "MaxID", required = true)
    protected String maxID;
    @XmlElement(required = true)
    protected String cStatus;
    @XmlElement(name = "ism_c_Serial", required = true)
    protected String ismCSerial;
    @XmlElement(name = "iim_c_Model", required = true)
    protected String iimCModel;

    /**
     * Gets the value of the maxID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxID() {
        return maxID;
    }

    /**
     * Sets the value of the maxID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxID(String value) {
        this.maxID = value;
    }

    /**
     * Gets the value of the cStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCStatus() {
        return cStatus;
    }

    /**
     * Sets the value of the cStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCStatus(String value) {
        this.cStatus = value;
    }

    /**
     * Gets the value of the ismCSerial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsmCSerial() {
        return ismCSerial;
    }

    /**
     * Sets the value of the ismCSerial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsmCSerial(String value) {
        this.ismCSerial = value;
    }

    /**
     * Gets the value of the iimCModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIimCModel() {
        return iimCModel;
    }

    /**
     * Sets the value of the iimCModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIimCModel(String value) {
        this.iimCModel = value;
    }


}
